### ISSUE TITLE
_tkinter.TclError: can't invoke "destroy" command:  application has been destroyed

### ISSUE THREAD

**Issue by faketooth** [faketooth/OMOOC2py#3]
执行`Python`官方文档给出的`Tkinter`样例代码，鼠标关闭窗口，`shell`中发现错误信息：

```
Traceback (most recent call last):
  File "ASimpleHelloWorldProgram.py", line 31, in <module>
    root.destroy() 
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1859, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command:  application has been destroyed
```

运行效果

![asimplehelloworldprogram-0](https://cloud.githubusercontent.com/assets/1687273/10694407/8a1bdf58-79d0-11e5-946f-70faacf22b67.png)

**Comment by faketooth** [comment]
运行效果有问题，bug原因：

`Application`类的`__init__`方法缩进未正确对齐，多缩进一层。
修复之后运行效果如下
![asimplehelloworldprogram-1](https://cloud.githubusercontent.com/assets/1687273/10694510/25c36a7a-79d1-11e5-85b2-3fdc702792c9.png)

**Comment by faketooth** [comment]
确定为bug，而且可以说是来自官方的恶意。以下分析基于官方[Issue14163](http://bugs.python.org/issue14163)和[python-list讨论](http://python.6.x6.nabble.com/Is-it-necessary-to-call-Tk-when-writing-a-GUI-app-with-Tkinter-td4530117.html)：

`_tkinter.TclError: can't invoke "destroy" command:  application has been destroyed`的问题只有在鼠标点击[x]的时候才会出现，点击`QUIT`按钮的时候不会报错。问题的原因就是在于那行`root.destroy()`，删了就完事儿了。

Rick Johnson对此的解释是官方文档是有错误的，并请求给出对应文档的链接，他们要把它钉死在耻辱墙上。虽然官方`issue14163`里显示，确实修复了文档中的示例代码，一瞅在线文档，[你们这是在搞什么鬼](https://docs.python.org/2/library/tkinter.html#a-simple-hello-world-program)

这还不算完！！！

`issue14613`的提交者声称，学习编程必须`Hello World`啊，`Hello`太没有诚意了！

```
def createWidgets(self):
    self.QUIT = Button(self)
    self.QUIT["text"] = "QUIT"
    self.QUIT["fg"] = 'red'
    self.QUIT["command"] = self.quit

    self.QUIT.pack({"side": "left"})

    self.hi_there = Button(self)
    self.hi_there["text"] = "Hello World",
    self.hi_there["command"] = self.say_hi

    self.hi_there.pack({"side": "left"})
```

结果你猜怎么着：
![image](https://cloud.githubusercontent.com/assets/1687273/10697855/877a27e0-79e0-11e5-81a1-2fb25237d08d.png)

对于这一对神秘的花括号，官方解释说：**嘛，这个问题其实挺微妙的~原因在于那行代码最后多了一个逗号，导致字符串变成了只有一个元素的元组，删了就ok了**。

真是呵呵哒：
![image](https://cloud.githubusercontent.com/assets/1687273/10697994/3fdf2ef2-79e1-11e5-92d1-de88b49d5c79.png)
