### ISSUE TITLE
_tkinter.TclError: can't pack ".4330939672.4331056088": it's a top-level window

### ISSUE THREAD

**Issue by faketooth** [faketooth/OMOOC2py#4]
```
from Tkinter import *

class Application(Frame):

    def foo(self):
        print 'foo'

    def createWidgets(self):
            text = Entry(self, background = 'red')
            text.pack()

            menu = Menu(self)
            menu.add_command(label="Hello", command='foo')
            menu.pack()

    def __init__(self, master=None):
            Frame.__init__(self, master)
            self.pack()
            self.createWidgets()

app = Application()
app.mainloop()
```

执行之后报错：

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    app = Application()
  File "main.py", line 22, in __init__
    self.createWidgets()
  File "main.py", line 17, in createWidgets
    menu.pack()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1940, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: can't pack ".4330939672.4331056088": it's a top-level window
```

**Comment by faketooth** [comment]
`Menu`控件的布局既不是`pack`也不是`grid`，因此方法调用错误。
要显示`Menu`，代码修改如下：

```
menubar = Menu(root)
file = Menu(menubar)
file.add_command(label="File", command=self.foo)
file.add_command(label="Quit", command=self.foo)
menubar.add_cascade(label="File", menu=file)
root.config(menu=menubar)
```

![2015-10-25 02 02 58](https://cloud.githubusercontent.com/assets/1687273/10711901/91367554-7abc-11e5-9be9-330cf26aacca.png)

**Comment by faketooth** [comment]
python/Tkinter 15种控件简介

1.Button 按钮。类似标签,但提供额外的功能,例如鼠标掠过、按下、释放以及键盘操作/事件
2.Canvas 画布。提供绘图功能(直线、椭圆、多边形、矩形)   ;可以包含图形或位图
3.Checkbutton 选择按钮。一组方框,可以选择其中的任意个(类似 HTML 中的 checkbox)
4.Entry   文本框。单行文字域,用来收集键盘输入(类似 HTML 中的 text)
5.Frame   框架。包含其他组件的纯容器
6.Label    标签。用来显示文字或图片
7.Listbox 列表框。一个选项列表,用户可以从中选择
8.Menu     菜单。点下菜单按钮后弹出的一个选项列表,用户可以从中选择
9.Menubutton 菜单按钮。用来包含菜单的组件(有下拉式、层叠式等等)
10.Message 消息框。类似于标签,但可以显示多行文本
11.Radiobutton 单选按钮。一组按钮,其中只有一个可被“按下” (类似 HTML 中的 radio)
12.Scale    进度条。线性“滑块”组件,可设定起始值和结束值,会显示当前位置的精确值
13.Scrollbar   滚动条。对其支持的组件(文本域、画布、列表框、文本框)提供滚动功能
14.Text     文本域。 多行文字区域,可用来收集(或显示)用户输入的文字(类似 HTML 中的 textarea)
15.Toplevel    顶级。类似框架,但提供一个独立的窗口容器。
